import { AnimalPassport, TriageScenario, StepJourney, ArchitectureItem } from "@/types";

export const SAMPLE_PASSPORTS: Record<string, AnimalPassport> = {
  cattle: {
    id: "VET-982410-IN",
    tagNumber: "IN-MH-14-84920",
    name: "Gauri (गौरी)",
    species: "Cattle",
    breed: "Gir (Indigenous Zebu)",
    gender: "Female",
    ageMonths: 42,
    dob: "2023-02-14",
    weightKg: 385,
    ownerName: "Rameshwar Patil",
    farmLocation: "Baramati, Pune District, Maharashtra",
    healthScore: 96,
    status: "Healthy",
    vaccineStatus: "Up to Date",
    qrData: "vetra://passport/IN-MH-14-84920?owner=Rameshwar&hash=8f1c79a9",
    avatarUrl: "/branding/vetra_icon.png",
    latestVitals: {
      temperature: "38.6 °C (Normal)",
      pulseRate: "64 bpm",
      respiratoryRate: "24 breaths/min",
      lastRecorded: "2026-08-18 (Field Visit #41)",
    },
    vaccines: [
      {
        name: "Foot & Mouth Disease (FMD) Quadrivalent",
        dateAdministered: "2026-04-12",
        nextDueDate: "2026-10-12",
        batchNumber: "FMD-BN-8839",
        veterinarian: "Dr. Arvind Deshmukh (VCI #8491)",
        status: "Completed",
      },
      {
        name: "Lumpy Skin Disease (LSD) Heterologous",
        dateAdministered: "2026-02-10",
        nextDueDate: "2027-02-10",
        batchNumber: "LSD-GTP-492",
        veterinarian: "Dr. Arvind Deshmukh (VCI #8491)",
        status: "Completed",
      },
      {
        name: "Hemorrhagic Septicemia (HS) Adjuvant",
        dateAdministered: "2025-11-05",
        nextDueDate: "2026-11-05",
        batchNumber: "HS-ADJ-1104",
        veterinarian: "Dr. Arvind Deshmukh (VCI #8491)",
        status: "Completed",
      },
      {
        name: "Black Quarter (BQ) Polyvalent Booster",
        dateAdministered: "2025-09-20",
        nextDueDate: "2026-09-20",
        batchNumber: "BQ-BOOST-302",
        veterinarian: "Dr. Priya Kulkarni (VCI #9204)",
        status: "Scheduled",
      },
    ],
    evmrRecords: [
      {
        id: "EVMR-2026-0814-01",
        date: "2026-08-14",
        diagnosis: "Mild Subclinical Mastitis (Right Fore Quarter)",
        veterinarian: "Dr. Arvind Deshmukh (BVSc & AH, VCI #8491)",
        clinicName: "Baramati Rural Veterinary Polyclinic",
        symptoms: ["Slight drop in morning yield (-1.2L)", "Mild flocculation on California Mastitis Test (CMT +1)", "No systemic pyrexia"],
        prescriptions: [
          {
            drug: "Cefquinome Sulfate Intramammary Infusion",
            dosage: "75 mg per affected quarter",
            frequency: "Once daily after milking",
            durationDays: 3,
            withdrawalPeriodDays: 4,
          },
          {
            drug: "Meloxicam Bolus",
            dosage: "100 mg orally",
            frequency: "Once daily with jaggery",
            durationDays: 3,
            withdrawalPeriodDays: 5,
          },
        ],
        notes: "Routine California Mastitis Test confirmed +1 trace. Udder softness maintained. Milk withholding period till 2026-08-21 strictly enforced to prevent antibiotic residues in cooperative supply.",
      },
      {
        id: "EVMR-2026-0502-03",
        date: "2026-05-02",
        diagnosis: "Routine Post-Partum Gynecology & Calving Evaluation",
        veterinarian: "Dr. Priya Kulkarni (MVSc Theriogenology, VCI #9204)",
        clinicName: "Mobile Veterinary Clinic #04",
        symptoms: ["45 days post-calving", "Clear lochial discharge", "Normal uterine involution"],
        prescriptions: [
          {
            drug: "Mineral Mixture & Chelated Calcium Supplement",
            dosage: "50 grams / day",
            frequency: "Daily in feed",
            durationDays: 60,
            withdrawalPeriodDays: 0,
          },
        ],
        notes: "Healthy uterine involution completed. Follicular activity visible on ultrasound. Ready for artificial insemination in next estrus cycle.",
      },
    ],
  },
  buffalo: {
    id: "VET-672911-IN",
    tagNumber: "IN-HR-06-39104",
    name: "Kaali (काली)",
    species: "Buffalo",
    breed: "Murrah (High Fat Yielding)",
    gender: "Female",
    ageMonths: 54,
    dob: "2022-02-10",
    weightKg: 540,
    ownerName: "Suraj Bhan Sharma",
    farmLocation: "Karnal, Haryana",
    healthScore: 91,
    status: "Healthy",
    vaccineStatus: "Up to Date",
    qrData: "vetra://passport/IN-HR-06-39104?owner=SurajBhan&hash=3b20e981",
    avatarUrl: "/branding/vetra_icon.png",
    latestVitals: {
      temperature: "37.9 °C (Normal)",
      pulseRate: "52 bpm",
      respiratoryRate: "18 breaths/min",
      lastRecorded: "2026-08-15 (Clinic Inspection)",
    },
    vaccines: [
      {
        name: "Hemorrhagic Septicemia (HS) + BQ Combined",
        dateAdministered: "2026-05-18",
        nextDueDate: "2027-05-18",
        batchNumber: "HSBQ-2026-94",
        veterinarian: "Dr. Harish Malik (VCI #6712)",
        status: "Completed",
      },
      {
        name: "Brucellosis S19 Strain (Heifer)",
        dateAdministered: "2022-08-10",
        nextDueDate: "Life Immunity",
        batchNumber: "BRUC-S19-901",
        veterinarian: "Dr. Harish Malik (VCI #6712)",
        status: "Completed",
      },
    ],
    evmrRecords: [
      {
        id: "EVMR-2026-0610-09",
        date: "2026-06-10",
        diagnosis: "Simple Indigestion / Ruminal Atony",
        veterinarian: "Dr. Harish Malik (BVSc, VCI #6712)",
        clinicName: "Karnal Central Animal Care Centre",
        symptoms: ["Reduced appetite after sudden feed shift", "Rumen motility 1 contraction / 3 min", "Mild bloating"],
        prescriptions: [
          {
            drug: "Rumenotorics & Live Yeast Culture Bolus",
            dosage: "2 boluses twice daily",
            frequency: "Morning and Evening",
            durationDays: 4,
            withdrawalPeriodDays: 0,
          },
        ],
        notes: "Restored regular rumination within 48 hours. Advised gradual transition between dry fodder and fresh green sorghum.",
      },
    ],
  },
  goat: {
    id: "VET-110943-IN",
    tagNumber: "IN-RJ-21-11928",
    name: "Rani (रानी)",
    species: "Goat",
    breed: "Sirohi (Dual Purpose Meat & Milk)",
    gender: "Female",
    ageMonths: 22,
    dob: "2024-10-18",
    weightKg: 42,
    ownerName: "Devi Singh Rathore",
    farmLocation: "Nagaur, Rajasthan",
    healthScore: 89,
    status: "Observation",
    vaccineStatus: "Due Soon",
    qrData: "vetra://passport/IN-RJ-21-11928?owner=DeviSingh&hash=9c4a88f1",
    avatarUrl: "/branding/vetra_icon.png",
    latestVitals: {
      temperature: "39.1 °C (Normal for Caprine)",
      pulseRate: "78 bpm",
      respiratoryRate: "28 breaths/min",
      lastRecorded: "2026-08-19 (Routine Camp)",
    },
    vaccines: [
      {
        name: "Peste des Petits Ruminants (PPR) Live Attenuated",
        dateAdministered: "2025-08-30",
        nextDueDate: "2028-08-30",
        batchNumber: "PPR-LIV-092",
        veterinarian: "Dr. Vikram Joshi (VCI #1184)",
        status: "Completed",
      },
      {
        name: "Enterotoxemia (ET) Vaccine Booster",
        dateAdministered: "2025-09-12",
        nextDueDate: "2026-09-12",
        batchNumber: "ET-TOX-741",
        veterinarian: "Dr. Vikram Joshi (VCI #1184)",
        status: "Scheduled",
      },
    ],
    evmrRecords: [
      {
        id: "EVMR-2026-0720-04",
        date: "2026-07-20",
        diagnosis: "Routine Deworming & Parasite Control",
        veterinarian: "Dr. Vikram Joshi (BVSc, VCI #1184)",
        clinicName: "Nagaur Block Veterinary Dispensary",
        symptoms: ["Mild ocular conjunctiva pallor (FAMACHA Score 2)", "Rough hair coat"],
        prescriptions: [
          {
            drug: "Ivermectin Oral Drench",
            dosage: "0.2 mg/kg bodyweight",
            frequency: "Single oral dose",
            durationDays: 1,
            withdrawalPeriodDays: 14,
          },
        ],
        notes: "Preventive monsoon deworming administered. FAMACHA score improved to Grade 1. Follow-up booster scheduled post-harvest.",
      },
    ],
  },
};

export const TRIAGE_SCENARIOS: TriageScenario[] = [
  {
    id: "scen-1",
    title: "High Fever + Drooling & Foot Lameness (Suspected Contagious)",
    species: "Cattle (Adult Cow)",
    symptoms: ["Rectal temperature 40.8°C", "Excessive ropey salivation", "Reluctance to bear weight on hind hoof", "Visible vesicular lesions on tongue border"],
    severity: "HIGH",
    aiConfidence: 94,
    differentialDiagnosis: [
      "Foot and Mouth Disease (FMD) — High Clinical Suspicion",
      "Vesicular Stomatitis",
      "Bovine Viral Diarrhea (BVD) Mucosal Disease",
      "Traumatic Glossitis / Hoof Trauma",
    ],
    recommendedAction: "ISOLATE ANIMAL IMMEDIATELY. Contact nearest verified veterinarian for urgent diagnostic swab and official ring-vaccination reporting.",
    suggestedQuestions: [
      "Are other animals in the herd showing reduced feed intake or similar drooling?",
      "When was the last FMD vaccination administered?",
      "Has any new animal entered the shed in the past 14 days?",
    ],
    disclaimer: "Vetra AI triage is a preliminary clinical decision-support tool and does NOT replace a licensed veterinary physician's physical examination.",
  },
  {
    id: "scen-2",
    title: "Lumpy Skin Nodules + Swollen Prescapular Lymph Nodes",
    species: "Cattle (Heifer)",
    symptoms: ["Firm circumscribed skin nodules (2-5cm across neck & flank)", "Mild pyrexia (39.9°C)", "Reduced water intake", "Bilateral nasal discharge"],
    severity: "HIGH",
    aiConfidence: 91,
    differentialDiagnosis: [
      "Lumpy Skin Disease (Capripoxvirus) — Primary Suspicion",
      "Pseudo-Lumpy Skin (Bovine Herpesvirus-2)",
      "Cutaneous Streptothricosis (Dermatophilosis)",
      "Urticaria / Allergic Reaction",
    ],
    recommendedAction: "Apply fly repellent / mosquito netting around stall. Schedule urgent veterinary consultation for symptomatic antipyretic care and secondary infection control.",
    suggestedQuestions: [
      "Is insect/vector pressure (flies, ticks, mosquitoes) high around the barn?",
      "Are there swelling lesions on the brisket or lower limbs?",
    ],
    disclaimer: "Vetra AI provides triage assistance under ICAR & VCI guidelines. Prescriptions can only be authored by registered veterinarians.",
  },
  {
    id: "scen-3",
    title: "Bloat & Distended Left Flank Post-Green Forage Intake",
    species: "Buffalo (Milking)",
    symptoms: ["Tense drum-like left paralumbar fossa", "Frequent kicking at belly", "Rapid shallow respiration", "Labored groaning"],
    severity: "EMERGENCY",
    aiConfidence: 96,
    differentialDiagnosis: [
      "Frothy Bloat (Alfalfa/Legume Indigestion)",
      "Free-Gas Bloat (Esophageal Obstruction / Choke)",
      "Traumatic Reticuloperitonitis (Hardware Disease)",
    ],
    recommendedAction: "URGENT CLINICAL EMERGENCY. Keep animal standing with front quarters elevated. Administer antifoaming agent if instructed by vet. Prepare doctor visit immediately.",
    suggestedQuestions: [
      "Did the animal consume wet clover, young lush lucerne, or damp concentrates today?",
      "Can the animal swallow water or is regurgitation occurring?",
    ],
    disclaimer: "Emergency triage protocol. Contact the emergency veterinary hotline immediately.",
  },
];

export const JOURNEY_STEPS: StepJourney[] = [
  {
    number: "01",
    title: "Instant Animal Registration & Secure QR Tagging",
    badge: "Under 60 Seconds",
    tagline: "Digitize your entire livestock in minutes with photo and biometric tagging.",
    description: "Farmers or field community workers register cattle, buffaloes, or goats via phone camera. An immutable Digital Animal Passport is generated instantly with an offline-compatible QR code.",
    bulletPoints: [
      "Offline registration without requiring active cellular internet",
      "Unique biometric & ear-tag matching to prevent duplicate identity",
      "Printable or silicone-tag scannable QR passport",
    ],
    icon: "QrCode",
    highlightColor: "#52B788",
  },
  {
    number: "02",
    title: "AI-Powered Contextual Symptom Screening",
    badge: "Assistive Decision Support",
    tagline: "Preliminary triage in farmer's native tongue (Hindi, Marathi, English).",
    description: "Farmers describe symptoms through voice, text, or photo. The Vetra AI Engine evaluates localized disease patterns and assigns a clinical urgency rating (Green/Amber/Red) while maintaining veterinary authority.",
    bulletPoints: [
      "Trained on validated ICAR & veterinary clinical diagnostic models",
      "Instant first-aid and quarantine containment guidance",
      "Clear escalation triggers to licensed veterinary officers",
    ],
    icon: "Bot",
    highlightColor: "#2D6A4F",
  },
  {
    number: "03",
    title: "Verified Veterinarian Geo-Dispatch",
    badge: "100% VCI Registered Doctors",
    tagline: "Instant connection with licensed veterinary professionals within 15 km.",
    description: "Vetra matches the case to certified practitioners based on clinical specialization and GPS proximity. Both farmer and doctor receive structured preliminary vitals before arrival.",
    bulletPoints: [
      "Government & private veterinarian network verification",
      "Automated turn-by-turn navigation for rural field visits",
      "Direct tele-triage video consult option for minor queries",
    ],
    icon: "Stethoscope",
    highlightColor: "#52B788",
  },
  {
    number: "04",
    title: "90-Second Electronic Veterinary Record (EVMR)",
    badge: "Clinical Speed & Precision",
    tagline: "Complete structured charting with automated dosage and withdrawal periods.",
    description: "During field visits, veterinarians scan the animal tag to unlock full medical lineage. They chart diagnoses, administer vaccines, and generate digital prescriptions in under 90 seconds.",
    bulletPoints: [
      "Calculates bodyweight-adjusted dosages automatically",
      "Automated milk & meat withdrawal period tracking (AMR protection)",
      "Offline sync automatically pushes records upon network reconnection",
    ],
    icon: "FileCheck2",
    highlightColor: "#2D6A4F",
  },
  {
    number: "05",
    title: "Continuous Epidemiological Intelligence",
    badge: "One-Health Ecosystem",
    tagline: "Protecting herd health and rural dairy economies from outbreaks.",
    description: "Anonymized, real-time clinical telemetry streams into public health and cooperative dashboards. Disease hot-spots trigger automatic ring-vaccination alerts to neighboring farms.",
    bulletPoints: [
      "Early warning alerts for Lumpy Skin, FMD, Anthrax, and Brucellosis",
      "Immutable provenance proof for dairy cooperative procurement",
      "Higher livestock valuation and seamless insurance verification",
    ],
    icon: "Activity",
    highlightColor: "#52B788",
  },
];

export const ARCHITECTURE_STACK: ArchitectureItem[] = [
  {
    layer: "Mobile Client (Farmer & Vet)",
    title: "Flutter 3.x + Offline SQLite Store",
    specs: "Dart • Clean Architecture • Riverpod • Deterministic Sync Engine",
    details: [
      "Sub-100ms response time on low-end Android 9+ devices",
      "Local-first SQLite with vector timestamp conflict resolution",
      "Trilingual localization (English, Hindi, Marathi)",
      "AES-256 local encrypted cache for biometric & medical data",
    ],
    iconName: "Smartphone",
  },
  {
    layer: "Backend Application Engine",
    title: "Spring Boot 3.3 LTS + Java 21",
    specs: "Enterprise Microservices • Spring Security 6 • Docker • AWS ECS",
    details: [
      "High-throughput RESTful & WebSocket API gateways",
      "Stateless JWT authorization with fine-grained RBAC (Farmer / Vet / Admin)",
      "Strict schema-level multi-tenancy & cooperative data boundaries",
      "Integrated OpenAPI 3.0 / Swagger living contracts",
    ],
    iconName: "Server",
  },
  {
    layer: "Persistence & Caching",
    title: "PostgreSQL 16 RDS + Redis Cluster",
    specs: "ACID Compliance • Point-in-Time Recovery • 99.99% Target Uptime",
    details: [
      "Relational integrity for immutable EVMR & vaccination registries",
      "PostGIS geospatial indices for fast 15km vet radius queries",
      "Sub-millisecond Redis session and hot disease telemetry caching",
      "Automated daily snapshot backups with encrypted storage",
    ],
    iconName: "Database",
  },
  {
    layer: "AI & Clinical Decision Engine",
    title: "ICAR-Aligned LLM & Vision Triage",
    specs: "Assistive Clinical Boundaries • Veterinary Authority Guardrails",
    details: [
      "Multi-modal image analysis for superficial dermatological screenings",
      "Dynamic prompt orchestration with verified veterinary knowledge bases",
      "Mandatory clinical non-prescription guardrails",
      "Continuous hallucination testing & veterinarian red-teaming",
    ],
    iconName: "Cpu",
  },
  {
    layer: "Cloud & Security Infrastructure",
    title: "AWS ap-south-1 (Mumbai Region)",
    specs: "Fargate Serverless • ALB • CloudWatch • Prometheus Telemetry",
    details: [
      "Low-latency domestic data residency compliant with Indian IT Act",
      "Auto-scaling from low dawn loads to heavy evening milking peaks",
      "Zero plain-text logging of personally identifiable information (PII)",
      "24/7 Micrometer & Grafana health monitoring",
    ],
    iconName: "Cloud",
  },
];

export const FAQS = [
  {
    question: "What is Vetra and who is it built for?",
    answer: "Vetra is a modern Veterinary Operating System (VetOS) built to transform livestock healthcare. It connects dairy and livestock farmers with certified licensed veterinarians through Digital Animal Passports, Electronic Veterinary Medical Records (EVMR), AI-assisted clinical triage, and real-time disease outbreak surveillance.",
  },
  {
    question: "Does the Vetra AI replace a licensed veterinarian?",
    answer: "Absolutely not. Vetra adheres strictly to Veterinary Council of India (VCI) regulations. Vetra's AI functions purely as a preliminary triage and decision-support tool—helping farmers recognize early disease signs, perform safe first-aid, and escalate urgently to licensed veterinarians. Only certified veterinarians can perform official examinations and write legal medical prescriptions.",
  },
  {
    question: "Does Vetra work in remote rural areas with no mobile internet?",
    answer: "Yes! Vetra is built from the ground up with an offline-first architecture. Farmers and veterinarians can register animals, scan QR passports, record vitals, and chart medical histories completely offline. All data is saved to a secure local database and automatically synchronizes deterministically once an internet connection is detected.",
  },
  {
    question: "How are veterinarians verified on the platform?",
    answer: "Every veterinarian registering on the Vetra Veterinary Network must submit their Veterinary Council of India (VCI) or State Veterinary Council registration number, degree credentials (BVSc & AH / MVSc), and government ID. Our compliance team verifies each registration with official council registries before granting EVMR prescribing privileges.",
  },
  {
    question: "How does Vetra help combat Antimicrobial Resistance (AMR)?",
    answer: "Vetra's EVMR engine features an automated withdrawal period tracker. When an antibiotic is prescribed, Vetra calculates the exact milk and meat withholding days based on the formulation and dosage. Farmers receive daily reminders not to supply milk during this window, preventing harmful antibiotic residues from entering the human food chain.",
  },
  {
    question: "Can dairy cooperatives or government bodies integrate with Vetra?",
    answer: "Yes. Vetra offers enterprise multi-tenant APIs and dashboards for dairy federations, breed societies, and state animal husbandry departments. Cooperatives can monitor aggregate herd health indices, track vaccination coverage across procurement routes, and verify provenance for export-grade milk.",
  },
  {
    question: "Where can I download the Vetra mobile app?",
    answer: "You can download the production Android release directly from this website (APK build) or request early beta access for iOS through TestFlight. Our team also provides on-ground onboarding support for dairy cooperatives and farmer groups.",
  },
];

export const METRICS = [
  { value: "100%", label: "VCI Verified Doctors", description: "Every practitioner vetted against council registries" },
  { value: "< 90s", label: "EVMR Charting Time", description: "Fastest digital field prescription workflow" },
  { value: "0 Internet", label: "Required In Field", description: "100% functional offline with local-first SQLite" },
  { value: "15 km", label: "Average Dispatch Radius", description: "Proximity-based rural veterinarian matching" },
];
